client:
  Common-Framework:
    uri: 'http://localhost:8080'
    prefix: /api/v1
    cf-api: /treasury/common-framework/move
    orchestrate-api: /treasury/common-framework/orchestrate
uuid: '59932'
excluded-folders:
  - REJ
  - TRASH_FILES
content-language: 'en'
inbox-path:
  - Users
  - JS59932
  - Desktop
  - TRR
  - inbox
outbox-path:
  - Users
  - JS59932
  - Desktop
  - TRR
  - outbox