client:
  Common-Framework:
    uri: 'http://trr-generic-c-common-framework.icg-msst-trr-165265.svc.cluster.local:8080'
    prefix: /api/v1
    cf-api: /treasury/common-framework/move
    orchestrate-api: /treasury/common-framework/orchestrate
uuid: '59932'
time-waited: 30
excluded-folders:
  - REJ
  - TRASH_FILES
content-language: 'en'
inbox-path:
  - inbox
outbox-path:
  - outbox
temp-path:
  - temporal