properties:
  success: 1
  client:
    trr:
      uri: http://localhost:8081/api/v1/trr
      api:
        create_folder: /create-folder
        delete_file: /delete-file
        exists: /exists
        move_file: /move-file
        read_file: /read-file
        rename_file: /rename-file
      path: path
      path_file: path_file
      file_name: file_name
      folder_name: folder_name
      new_file_name: new_file_name
      origin_path: origin_path
      destination_path: destination_path
      suffix: suffix
  accept:
    name: accept
  contentType:
    name: content-type
  contentLanguage:
    name: content-language
  uuid:
    name: uuid
  fileName:
    name: file_name
  path:
    name: path
    pattern: '.*[*?"<>|].*'
  outbox:
    dir:
      date-format: '%Y%m%d'
  volume:
    destination: "C:\\Users\\JS59932\\Desktop\\TRR\\outbox2"
  trashFiles:
    destination: "C:\\Users\\JS59932\\Desktop\\TRR\\outbox\\TRASH_FILES2"
  controller:
    format: application/json
    response:
      format: application/json
    uri:
      common-framework: /common-framework/move
  interface_name: interface_name
  date_book: date_book

db:
  date-format: '%d-%b-%y'
  date-patterns:
    DDMMYY: 
      - "^(0[1-9]|[1-2][0-9]|3[0-1])(0[1-9]|1[0-2])([0-9]{2})$"
      - "%d%m%y"
    YYYYMM: 
      - "^([0-9]{4})(0[1-9]|1[0-2])$"
      - "%Y%m"
    DD-MM-YYYY: 
      - "^(0[1-9]|[1-2][0-9]|3[0-1])[-](0[1-9]|1[0-2])[-]([0-9]{4})$"
      - "%d-%m-%Y"
    YYMMDD: 
      - "^([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])$"
      - "%y%m%d"
    DD/MM/YYYY: 
      - "^(0[1-9]|[1-2][0-9]|3[0-1])[/](0[1-9]|1[0-2])[/]([0-9]{4})$"
      - "%d/%m/%Y"
    MMDDYYYY: 
      - "^(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])([0-9]{4})$"
      - "%m%d%Y"
    YYYYMMDD: 
      - "^(([0-9]{4})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))$"
      - "%Y%m%d"
    DD MMM YYYY: 
      - ("^(([1-9])|([0][1-9])|([1-2][0-9])|([3][0-1]))[ \-](JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)[ \-]\d{2}$")
      - "%d %b %y"
  host: 'oraasgtd65-scan.nam.nsroot.net'
  user: 'TRR_DEVS'
  password: 'eWlDNzZCOFU='
  patterns:
    - "(0[1-9]|[1-2][0-9]|3[0-1])[-](0[1-9]|1[0-2])[-]([0-9]{4})"
    - "(0[1-9]|[1-2][0-9]|3[0-1])[/](0[1-9]|1[0-2])[/]([0-9]{4})"
    - "(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])([0-9]{4})"
    - "(([0-9]{4})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1]))"
    - "(0[1-9]|[1-2][0-9]|3[0-1])(0[1-9]|1[0-2])([0-9]{2})"
    - "([0-9]{2})(0[1-9]|1[0-2])(0[1-9]|[1-2][0-9]|3[0-1])"
    - "([0-9]{4})(0[1-9]|1[0-2])"
  port: '8889'
  sid: 'TRRMX1D'
  tables:
    da-file-receipt: 
      name: DA_FILE_RECEIPT
      foreign-key: "DA_INTERFACE.interface_name"
    da-interface: 
      name: DA_INTERFACE
      relantioship: DaFileReceipt
      interface_active: A
    da_process_status:
      initial_status: ON_ICE
    status:
      waiting: WAITING
      success: SUCCESS

exception:
  connection-trr:
    details: No connection could be made to TRR
    location: connection
  file-not-found:
    details: file cannot be located
    location: FileName
  interface-not-found:
    details: Interface cannot be located or validated 
    location: File
  bad-request:
    details: Invalid request body
    location: Request
  forbidden:
    details: Forbidden
    location: Forbidden
  notFound:
    details: The requested resource was not found
    location: Path
  methodNotAllowed:
    details: Method not allowed
    location: Method
  serverError:
    details: Internal server error
    location: Server
  noDatabase:
    details: Database conection error
    location: Database
  fileName:
    details: fileName cannot be empty
    location: fileName
  path:
    empty:
      details: Path cannot be empty
      location: path
    type: 
      details: Invalid Request Body
      location: path
    invalid:
      details: Path contains invalid characters
      location: path
  fileDate:
    details: Date not Found
    location: File
  moveFile:
    details: Could not move file
    locatin: file
  accept:
    empty:
      details: Accept header cannot be null nor empty
      location: accept
    mimeType:
      details: Not acceptable
      location: accept
  contentType:
    empty:
      details: Unsupported Media-Type
      location: content-type
    mimeType:
      details: Unsupported Media-Type
      location: content-type
  contentLanguage:
    empty:
      details: Content-language header cannot be emtpy
      location: content-language
    format:
      details: Content-language header is not valid, should be only
      location: content-language
  uuid:
    empty:
      details: uuid header cannot be null nor empty
      location: uuid
      
log:
  info:
    controller:
      headers: 'Controller arrived with headers'
      request: 'Request received %s'
  dao:
    da_file_receipt:
      insert: 'Inserting into da file receipt %s'
      update_date: 'Updating process-date %s da file receipt'
      update_status: 'Updating status %s da file receipt'
    da_process_status:
      insert: 'Inserting into Da Process Status with %s'
      update_status: 'Updating status %s da process status'
      update_date: 'Updating process date %s da process status'
  error:
    exception_handler: 'Exception ocurred with %s'